// React/ventas.jsx
import React from 'react';

class Ventas extends React.Component{
  render() {
    return(
      <div class="container">
        <div class="row">
          <div class="col s8">
            <h1>Carrito de compras</h1>
          </div>
        </div>
        <div class="row">
          <div class="col s8">
            <div class="card horizontal">
              <div class="card-image">
                <img src="assets/images/{{item.template}}" class="responsive-img" />
              </div>
              <div class="card-stacked">
                <div class="card-content">
                  <h3>item.nombre</h3>
                  <p></p>
                  <p>Unidades: item.cantidad</p>
                  <p>Subtotal: item.subtotal</p>
                </div>
              </div>
            </div>
            </div>

          <div class="col s4">
            <div class="row">
              <div class="col s12">
                <h2>Total: total</h2>
              </div>
            </div>
            <div class="row">
              <div class="col s6">
                <a class="waves-effect waves-light btn">Cancelar</a>
              </div>
              <div class="col s6">
                <a class="waves-effect waves-light btn">Pagar</a>
              </div>
            </div>
          </div>
        </div>
      </div>

    )
  }
}

export default Ventas;

// Angular/my-app/src/app/ventas/ventas.component.ts
import { Component, OnInit } from '@angular/core';
import { ComprasService } from '../compras.service';

@Component({
  selector: 'app-ventas',
  templateUrl: './ventas.component.html',
  styleUrls: ['./ventas.component.css']
})
export class VentasComponent implements OnInit {

  total = this.compras.total;

  public productos:any = null;

  constructor(private compras : ComprasService) { }

  ngOnInit() {
    this.productos = this.compras.productosCarrito;
  }

}

<div class="container">
  <div class="row">
    <div class="col s8">
      <h1>Carrito de compras</h1>
    </div>
  </div>
  <div class="row">
    <div class="col s8" *ngFor="let item of productos">
      <div class="card horizontal">
        <div class="card-image">
          <img src="assets/images/{{item.template}}" class="responsive-img">
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <h3>{{item.nombre}}</h3>
            <p></p>
            <p>Unidades: {{item.cantidad}}</p>
            <p>Subtotal: {{item.subtotal}}</p>
          </div>
        </div>
      </div>
      </div>

    <div class="col s4">
      <div class="row">
        <div class="col s12">
          <h2>Total: {{total | currency}}</h2>
        </div>
      </div>
      <div class="row">
        <div class="col s6">
          <a class="waves-effect waves-light btn" (click)="cancelar()">Cancelar</a>
        </div>
        <div class="col s6">
          <a class="waves-effect waves-light btn" (click)="pagar()">Pagar</a>
        </div>
      </div>
    </div>
  </div>
</div>
