// ReactFin/rounting/src/login.jsx
import React from 'react';
import { Row, Col, TextInput, Icon, Button} from 'react-materialize';
import { getDatos } from './utils/httpService';
import { toast } from 'materialize-css';
import { Link, Redirect} from 'react-router-dom'
import { Router, Route, } from 'react-router';
import PropTypes from "prop-types";

class Login extends React.Component{

  constructor(){
    super ();
    this.state = {usuario:'',psw:'',log:false};
  }

  handleChange(event) {
    this.setState({usuario: event.target.value});
  }

  handleChangeP(event) {
    this.setState({psw: event.target.value});
  }

  login(e, usuario, psw){
    getDatos(usuario).then(response => {
      if (response.data == psw){
        localStorage.setItem('usuario', usuario);
        this.setState({log:true});
      }else{
        toast({
          html: 'Usuario o contraseña incorrecta',
          displayLength: 1000
        })
      }
    });
    e.preventDefault();
  }

  render() {
    if (this.state.log === true) {
      return <Redirect to='/principal/'/>
    }

    return(
      <div className="contenedor_principal">
        <div className="container">
          <Row>
            <Col s={4} offset="s4">
              <h1>LOGIN</h1>
            </Col>
          </Row>

          <form onSubmit={(e) => this.login(e,this.state.usuario,this.state.psw)}>
            <Row>
                <Col s={4} offset="s4">
                  <TextInput label="Usuario" validate required value={this.state.usuario} onChange={this.handleChange.bind(this)}/>
                </Col>
            </Row>

            <Row>
                <Col s={4} offset="s4">
                  <TextInput label="Password" password validate required value={this.state.psw} onChange={this.handleChangeP.bind(this)}/>
                </Col>
            </Row>

            <Row>
                <Col s={4} offset="s4">
                  <Button waves="light" type="submit">Ingresar
                      <Icon right>send</Icon>
                  </Button>
                </Col>
            </Row>
          </form>

        </div>
      </div>

    )
  }
}

export default Login;

// Angular/my-app/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { HttpService } from '../http.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers:[HttpService]
})
export class LoginComponent implements OnInit {

  constructor(private httpService : HttpService) { }

  public verificacion:any;

  ngOnInit() {

  }

  //submitted = false;

  //onSubmit() { this.submitted = true; }

  login(valor:any){
    this.httpService.getDatos(valor.usuario,valor.psw);
    //console.log(valor);
  }

}

<div class="contenedor_principal" style="padding: 0% !important;margin: 0% !important;">
  <div class="container">
    <div class="row">
      <div class="col s4 offset-s4">
        <h1>LOGIN</h1>
      </div>
    </div>

    <form #loginForm="ngForm" (ngSubmit)="login(loginForm.value)">
      <div class="row">
          <div class="input-field col s4 offset-s4">
            <input id="username" type="text" class="validate white-text" required name="usuario" ngModel>
            <label for="username">Usuario</label>
          </div>
      </div>

      <div class="row">
          <div class="input-field col s4 offset-s4">
            <input id="password" type="password" class="validate white-text" required name="psw" ngModel>
            <label for="password">Password</label>
          </div>
      </div>

      <div class="row">
          <div class="input-field col s4 offset-s4">
            <button class="btn waves-effect waves-light" type="submit" [disabled]="!loginForm.form.valid">Ingresar
                <i class="material-icons right">send</i>
            </button>
          </div>
      </div>
    </form>

  </div>
</div>
