// React/login.jsx
import React from 'react';
import { Row, Input, Col, TextInput, Icon } from 'react-materialize';

class Login extends React.Component{
  render() {
    return(
      <div className="contenedor_principal">
        <div className="container">
          <Row>
            <Col s={4} offset="s4">
              <h1>LOGIN</h1>
            </Col>
          </Row>

          <form>
            <Row>
                <Col s={4} offset="s4">
                  <TextInput label="Usuario" validate required/>
                </Col>
            </Row>

            <Row>
                <Col s={4} offset="s4">
                  <TextInput label="Password" password validate required/>
                </Col>
            </Row>

            <Row>
                <Col s={4} offset="s4">
                  <button waves="light" type="submit">Ingresar
                      <Icon right>send</Icon>
                  </button>
                </Col>
            </Row>
          </form>

        </div>
      </div>

    )
  }
}

export default Login;

// Angular/my-app/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { HttpService } from '../http.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers:[HttpService]
})
export class LoginComponent implements OnInit {

  constructor(private httpService : HttpService) { }

  ngOnInit() {
    this.httpService.getDatos();
  }

}

<div class="contenedor_principal" style="padding: 0% !important;margin: 0% !important;">
  <div class="container">
    <div class="row">
      <div class="col s4 offset-s4">
        <h1>LOGIN</h1>
      </div>
    </div>

    <form #loginForm="ngForm" (ngSubmit)="login(loginForm.value)">
      <div class="row">
          <div class="input-field col s4 offset-s4">
            <input id="username" type="text" class="validate white-text" required name="usuario" ngModel>
            <label for="username">Usuario</label>
          </div>
      </div>

      <div class="row">
          <div class="input-field col s4 offset-s4">
            <input id="password" type="password" class="validate white-text" required name="psw" ngModel>
            <label for="password">Password</label>
          </div>
      </div>

      <div class="row">
          <div class="input-field col s4 offset-s4">
            <button class="btn waves-effect waves-light" type="submit" [disabled]="!loginForm.form.valid">Ingresar
                <i class="material-icons right">send</i>
            </button>
          </div>
      </div>
    </form>

  </div>
</div>
